name: Continuous Integration

on:
  pull_request:
  push:
    branches:    
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.3', '7.4']
        dependencies: ['']
        phpunit-group: ['default']
        include:
          - { php-version: '7.3', dependencies: '--prefer-lowest' }
          - { php-version: '7.3', phpunit-group: 'integration' }
          - { php-version: '8.0', dependencies: '--ignore-platform-req=php' }

    continue-on-error: ${{ matrix.php-version == '8.0' }}
    name: PHP ${{ matrix.php-version }} ${{ matrix.dependencies }} (${{ matrix.phpunit-group }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-version }}
          extensions:
          coverage: none
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress ${{ matrix.dependencies }}

      - name: Execute tests
        env:
          SHIPANDCO_ACCESS_TOKEN: ${{ secrets.SHIPANDCO_ACCESS_TOKEN }}
        run: |
          make ci-test PHPUNIT_GROUP=${{ matrix.phpunit-group }}

      - name: Validate composer.json
        run: |
          composer validate --strict
          composer normalize --diff --dry-run
